news/urls.py
from django.urls import path
from .views import listaArticoliView,listaGiornalistiView,listaArticoliGiornalistaView
from . import views

app_name='news'
urlpatterns = [
    path('', views.home, name='home'),
    path('lista-giornalisti',  listaGiornalistiView.as_view(), name='lista_giornalisti'),
    path('lista-articoli', listaArticoliView.as_view(), name='lista_articoli'),
    path('lista-articoli-giornalista/<int:pk>', listaArticoliGiornalistaView, name='lista_articoli_giornalista'),
]

verifica_losa/urls.py
from django.contrib import admin
from django.urls import path, include
from news import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('news/', include('news.urls', namespace="news")),
]

news/models.py
from django.db import models
from django.contrib.auth.models import User

class Giornalista(models.Model):
    """ il modello generico di un giornalista """
    nome = models.CharField(max_length=20)
    cognome = models.CharField(max_length=20)
    def __str__(self):
        return self.nome + " " + self.cognome
    class Meta:
        verbose_name = "Giornalista"
        verbose_name_plural = "Giornalisti"

class Articolo(models.Model):
    """ il modello generico di un articolo di news """
    titolo = models.CharField(max_length=100) # alcuni campi necessitano di parametri obbligatori!
    contenuto = models.TextField()
    giornalista = models.ForeignKey(Giornalista, on_delete=models.CASCADE, related_name="articoli")
    def __str__(self):
        return self.titolo
    class Meta:
        verbose_name = "Articolo"
        verbose_name_plural = "Articoli"

news/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from .models import Articolo,Giornalista
from django.shortcuts import get_object_or_404

def home(request):
    return render(request, "home.html")

class listaArticoliView(ListView):
    model = Articolo
    template_name = 'news/articoli.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["articoli"] = Articolo.objects.all()
        return context

def listaArticoliGiornalistaView(request,pk):
    giornalista=get_object_or_404(Giornalista, id=pk)
    articoli=giornalista.articoli.all()
    context = {'giornalista': giornalista,
               'articoli': articoli,
               }
    return render(request, 'news/articoli.html', context)

class listaGiornalistiView(ListView):
    model = Giornalista
    template_name = 'news/giornalisti.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["giornalisti"] = Giornalista.objects.all()
        return context

templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="it">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{%block titolo%}Verifica{%endblock titolo%}</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <a class="navbar-brand" href="/">Web apps</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/"> <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              News
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'news:lista_articoli' %}">Lista articoli</a> 
              <a class="dropdown-item" href="{% url 'news:lista_giornalisti' %}">Lista giornalisti</a>
            </div>
          </li> 
        </ul>
      </div>
    </nav>
    <div class="container my-4">
      <h3>Verifica di Alessandro Losa</h3>
     {%block contenuti%}
     {%endblock contenuti%}
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

templates/home.html
{% extends 'base.html'%}
{%block contenuti%}
<div class="row">
    <div class="col-8">
        <div class="card my-2">
            <div class="card-header">
              <h3>VERIFICA DJANGO</h3>
            </div>
            <div class="card-body">
              <h3>Losa Alessandro</h3>
            </div>
            <div class="card-footer">
              <b>Eseguita il 20/05/2020 </b> 
            </div>
        </div>
    </div>
  </div>
{%endblock contenuti%}

templates/news/articoli.html
{% extends 'base.html' %}
{% block contenuti %}
    {% if giornalista %}
    <h5  class="my-3" >Elenco degli articoli di {{ giornalista.nome }} {{ giornalista.cognome }}:</h5>
    {% else %}
    <h5  class="my-3" >Elenco di tutti gli articoli:</a></h5>
    {% endif %}
  
    <div class="my-3"></div>
    {% for articolo in articoli %}
        <p>{{ forloop.counter }})  {{ articolo.titolo }}<br>
            {{ articolo.contenuto }}
            <small>({{ articolo.giornalista }})</small> 
        </p>
        
        <hr>
    {% endfor %}
</div>
{% endblock contenuti %}

templates/news/giornalisti.html
{% extends 'base.html' %}
{% block contenuti %}
    <h5  class="my-3" >Elenco di tutti i giornalisti:</a></h5>
    <div class="my-3"></div>
    {% for giornalista in giornalisti %}
        <p>{{ forloop.counter }})  
            <a href="{% url 'news:lista_articoli_giornalista' pk=giornalista.id %}">{{ giornalista.nome }} {{ giornalista.cognome }}</a>
        </p>
        <hr>
    {% endfor %}
</div>
{% endblock contenuti %}